## can be written in YAML format as well which is better in structure
## but if both .yml and .properties exists then priority will be given to
## .properties
## BUT USSE BHI PEHLE PRIORITY DI JAYEGI CMD LINE KO
#spring.application.name=JournalApp
#spring.data.mongodb.uri=mongodb+srv://shikshak013_db_user:UMHrfqsToPQGpDBE@cluster0.jvtyxvh.mongodb.net/?appName=Cluster0
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
## spring.servlet.context-path= /my-journal-app (base url)
